import argparse
import csv
import json
import shutil
import sys
from datetime import datetime
from pathlib import Path

# Add root folder to sys.path
sys.path.append(str(Path(__file__).resolve().parent.parent.parent))


def main():
    parser = argparse.ArgumentParser(description="Ultralytics YOLO Evaluation Runner (Validation/Test splits)")
    parser.add_argument(
        "--weights",
        type=str,
        required=True,
        help="Path to YOLO best.pt weights file"
    )
    parser.add_argument(
        "--data",
        type=str,
        default="data/processed/yolo_remapped/data.yaml",
        help="Path to dataset data.yaml file"
    )
    parser.add_argument(
        "--split",
        type=str,
        default="val",
        choices=["val", "test"],
        help="Split to evaluate on ('val' or 'test')"
    )
    parser.add_argument(
        "--project",
        type=str,
        default="runs/detect",
        help="Project output logging folder"
    )
    parser.add_argument(
        "--name",
        type=str,
        default="yolo_evaluation",
        help="Name of the evaluation run folder"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="reports/experiments/yolo_baseline",
        help="Path to copy validation visual charts"
    )

    args = parser.parse_args()

    weights_path = Path(args.weights)
    data_yaml = Path(args.data)
    output_dir = Path(args.output_dir)

    print("==================================================")
    print("YOLO Baseline Evaluation Runner")
    print(f"Weights:     {weights_path.resolve()}")
    print(f"data.yaml:   {data_yaml.resolve()}")
    print(f"Split:       {args.split}")
    print(f"Project:     {args.project}")
    print(f"Name:        {args.name}")
    print("==================================================")

    if not weights_path.exists():
        raise FileNotFoundError(f"Weights file not found at: {weights_path}")

    # Import ultralytics
    print("Importing YOLO module...")
    from ultralytics import YOLO

    model = YOLO(args.weights)

    print(f"Running validation on split '{args.split}'...")
    abs_project_path = str(Path(args.project).resolve())
    results = model.val(
        data=str(data_yaml.resolve()),
        split=args.split,
        project=abs_project_path,
        name=args.name,
        plots=True,
        save_json=True
    )

    # Print summary metrics
    # results object contains metrics:
    # results.results_dict -> dict containing metrics like metrics/precision, metrics/recall, metrics/mAP50, metrics/mAP50-95
    # Let's handle different ultralytics versions results structure safely:
    r_dict = getattr(results, "results_dict", {})
    precision = r_dict.get("metrics/precision(B)", results.box.mp)
    recall = r_dict.get("metrics/recall(B)", results.box.mr)
    map50 = r_dict.get("metrics/mAP50(B)", results.box.map50)
    map95 = r_dict.get("metrics/mAP50-95(B)", results.box.map)

    print("\n================ EVALUATION SUMMARY ================")
    print(f"Split:          {args.split}")
    print(f"Precision:      {precision:.4f}")
    print(f"Recall:         {recall:.4f}")
    print(f"mAP@0.5:        {map50:.4f}")
    print(f"mAP@0.5:0.95:   {map95:.4f}")
    print("====================================================")

    # Copy generated evaluation charts (PR curves, confusion matrices) to output_dir
    run_dir = Path(abs_project_path) / args.name
    if not run_dir.exists():
        nested_dir = Path(abs_project_path) / "runs/detect" / args.name
        if nested_dir.exists():
            run_dir = nested_dir

    if run_dir.exists():
        output_dir.mkdir(parents=True, exist_ok=True)
        print(f"\nCopying evaluation charts to: {output_dir.resolve()}")
        
        # Files generated by YOLO validation
        files_to_copy = [
            "confusion_matrix.png",
            "confusion_matrix_normalized.png",
            "F1_curve.png",
            "P_curve.png",
            "R_curve.png",
            "PR_curve.png",
            "val_batch0_pred.jpg",
            "val_batch0_labels.jpg"
        ]
        
        for fname in files_to_copy:
            src_file = run_dir / fname
            if not src_file.exists():
                # YOLOv8.4+ prefixes curve files with 'Box' (e.g. BoxPR_curve.png)
                src_file = run_dir / f"Box{fname}"
                
            if src_file.exists():
                dest_fname = f"{args.split}_{fname}"
                dest_file = output_dir / dest_fname
                shutil.copy2(src_file, dest_file)
                print(f"  Copied {src_file.name} -> {dest_fname}")
                
    # Save machine-readable metrics
    output_dir.mkdir(parents=True, exist_ok=True)
    model_name = weights_path.parent.parent.name if weights_path.parent.name == "weights" else weights_path.stem
    metrics_data = {
        "split": args.split,
        "precision": float(precision),
        "recall": float(recall),
        "mAP@0.5": float(map50),
        "mAP@0.5:0.95": float(map95),
        "weights_path": str(weights_path.resolve()),
        "data_path": str(data_yaml.resolve()),
        "timestamp": datetime.now().isoformat(),
        "model_name": model_name
    }
    
    json_path = output_dir / f"metrics_{args.split}.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(metrics_data, f, indent=2)
    print(f"Saved JSON metrics to: {json_path}")
    
    csv_path = output_dir / f"metrics_{args.split}.csv"
    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=metrics_data.keys())
        writer.writeheader()
        writer.writerow(metrics_data)
    print(f"Saved CSV metrics to: {csv_path}")
    
    print("\nEvaluation execution finished successfully!")


if __name__ == "__main__":
    main()
